packages:
  - apps/*
  - configs/*
  - packages/*

catalogs:
  base:
    '@standard-schema/spec': ^1.1.0
    arktype: ^2.1.29
    tsdown: ^0.18.0
    typescript: ^5.9.3
    valibot: ^1.2.0
    zod: ^4.2.0
  design:
    motion: ^12.34.3
  fumadocs:
    fumadocs-core: ^16.6.8
    fumadocs-mdx: ^14.2.9
    fumadocs-ui: ^16.6.8
  linting:
    '@biomejs/biome': ^2.4.4
    '@commitlint/cli': ^20.4.2
    '@commitlint/config-conventional': ^20.4.2
    ultracite: ^7.2.4
  next:
    '@takumi-rs/image-response': ^0.69.5
    next: ^16.1.6
  react:
    lucide-react: ^0.575.0
    react: ^19.2.4
    react-dom: ^19.2.4
  styling:
    '@tailwindcss/postcss': ^4.2.1
    postcss: ^8.5.6
    tailwind-merge: ^3.5.0
    tailwindcss: ^4.2.1
  testing:
    '@vitest/coverage-v8': ^4.0.15
    '@vitest/ui': ^4.0.18
    vitest: ^4.0.18
  tooling:
    '@changesets/cli': ^2.29.8
    '@turbo/gen': ^2.8.12
    lefthook: ^2.1.1
    nyc: ^18.0.0
    rimraf: ^6.1.3
    turbo: ^2.8.12
  types:
    '@types/mdx': ^2.0.13
    '@types/node': ^25.0.2
    '@types/react': ^19.2.14
    '@types/react-dom': ^19.2.3

onlyBuiltDependencies:
  - '@swc/core'
  - core-js-pure
  - esbuild
  - lefthook
  - sharp
