packages:
  - apps/*
  - configs/*
  - packages/*

onlyBuiltDependencies:
  - "@swc/core"
  - core-js-pure
  - esbuild
  - lefthook
  - sharp

catalogs:
  ai:
    "@ai-sdk/openai-compatible": ^1.0.28
    "@ai-sdk/react": ^2.0.104
    ai: ^5.0.104

  base:
    "@radix-ui/react-dialog": ^1.1.15
    "@radix-ui/react-slot": ^1.2.4
    class-variance-authority: ^0.7.1
    clsx: ^2.1.1
    lucide-react: ^0.555.0
    tailwind-merge: ^3.4.0
    typescript: ^5.9.3
    typescript-eslint: ^8.48.0
    tsdown: "^0.17.0-beta.3"
    zod: ^4.1.13

  fumadocs16:
    "fumadocs-core": ^16.2.0
    "fumadocs-mdx": ^14.0.4
    "fumadocs-typescript": ^4.0.13
    "fumadocs-ui": ^16.2.0

  next16:
    "@bprogress/next": ^3.2.12
    "@vercel/analytics": ^1.5.0
    next: ^16.0.5
    next-themes: ^0.4.6

  react19:
    "@vitejs/plugin-react": ^5.1.1
    babel-plugin-react-compiler: ^19.1.0-rc.3
    react: ^19.2.0
    react-dom: ^19.2.0

  tailwind4:
    "@tailwindcss/postcss": ^4.1.17
    "@tailwindcss/vite": ^4.1.17
    postcss: ^8.5.6
    tailwindcss: ^4.1.17
    tw-animate-css: ^1.4.0

  types:
    "@types/mdx": ^2.0.13
    "@types/node": ^24.10.1
    "@types/react": ^19.2.0
    "@types/react-dom": ^19.2.0

  testing:
    "@vitest/coverage-v8": ^4.0.14
    jsdom: ^27.2.0
    vitest: ^4.0.14
