packages:
  - apps/*
  - configs/*
  - packages/*

catalogs:
  base:
    '@standard-schema/spec': ^1.1.0
    arktype: ^2.1.29
    tsdown: ^0.18.0
    typescript: ^5.9.3
    valibot: ^1.2.0
    zod: ^4.2.0
  linting:
    '@biomejs/biome': ^2.3.15
    '@commitlint/cli': ^20.4.1
    '@commitlint/config-conventional': ^20.4.1
    ultracite: ^7.1.5
  testing:
    '@vitest/coverage-v8': ^4.0.15
    '@vitest/ui': ^4.0.18
    vitest: ^4.0.18
  tooling:
    '@changesets/cli': ^2.29.8
    '@turbo/gen': ^2.8.7
    lefthook: ^2.1.1
    rimraf: ^6.1.3
    turbo: ^2.8.7
  types:
    '@types/node': ^25.0.2
  vitepress:
    '@shikijs/vitepress-twoslash': ^3.20.0
    vitepress: ^2.0.0-alpha.15
    vitepress-plugin-llms: ^1.9.3

onlyBuiltDependencies:
  - '@swc/core'
  - core-js-pure
  - esbuild
  - lefthook
