packages:
  - apps/*
  - configs/*
  - packages/*

catalogs:
  base:
    '@standard-schema/spec': ^1.0.0
    arktype: ^2.1.28
    tsdown: ^0.17.3
    typescript: ^5.9.3
    valibot: ^1.2.0
    zod: ^4.1.13
  elysia:
    elysia: ^1.4.19
  hono:
    hono: ^4.11.0
  linting:
    '@biomejs/biome': ^2.3.8
    '@commitlint/cli': ^20.2.0
    '@commitlint/config-conventional': ^20.2.0
    ultracite: ^6.4.0
  next:
    next: ^16.0.10
  react:
    '@types/react': ^19.2.7
    react: ^19.2.3
  tanstack:
    '@tanstack/react-router': ^1.141.2
  testing:
    '@vitest/coverage-v8': ^4.0.15
    '@vitest/ui': ^4.0.15
    vitest: ^4.0.15
  tooling:
    '@changesets/cli': ^2.29.8
    '@turbo/gen': ^2.6.3
    lefthook: ^2.0.9
    rimraf: ^6.1.2
    turbo: ^2.6.3
  types:
    '@types/node': ^25.0.1
  vitepress:
    '@shikijs/vitepress-twoslash': ^3.20.0
    vitepress: ^1.6.4
    vitepress-plugin-llms: ^1.9.3

onlyBuiltDependencies:
  - '@swc/core'
  - core-js-pure
  - esbuild
  - lefthook
  - sharp
