packages:
  - apps/*
  - configs/*
  - packages/*

catalogs:
  base:
    '@standard-schema/spec': ^1.1.0
    arktype: ^2.1.29
    tsdown: ^0.18.0
    tsx: ^4.21.0
    typescript: ^5.9.3
    valibot: ^1.2.0
    zod: 4.2.0
  linting:
    '@biomejs/biome': ^2.3.11
    '@commitlint/cli': ^20.3.1
    '@commitlint/config-conventional': ^20.3.1
    ultracite: ^7.0.11
  mcp:
    '@modelcontextprotocol/sdk': ^1.25.2
  testing:
    '@vitest/coverage-v8': ^4.0.15
    '@vitest/ui': ^4.0.17
    vitest: ^4.0.17
  tooling:
    '@changesets/cli': ^2.29.8
    '@turbo/gen': ^2.7.4
    lefthook: ^2.0.14
    rimraf: ^6.1.2
    turbo: ^2.7.4
  types:
    '@types/node': ^25.0.2
  vitepress:
    '@shikijs/vitepress-twoslash': ^3.20.0
    vitepress: ^2.0.0-alpha.15
    vitepress-plugin-llms: ^1.9.3

onlyBuiltDependencies:
  - '@swc/core'
  - core-js-pure
  - esbuild
  - lefthook
