packages:
  - apps/*
  - configs/*
  - packages/*

catalogs:
  ai:
    "@ai-sdk/openai-compatible": ^1.0.28
    "@ai-sdk/react": ^2.0.106
    ai: ^5.0.106
  base:
    "@radix-ui/react-dialog": ^1.1.15
    "@radix-ui/react-slot": ^1.2.4
    arktype: ^2.1.28
    class-variance-authority: ^0.7.1
    clsx: ^2.1.1
    lucide-react: ^0.555.0
    tailwind-merge: ^3.4.0
    tsdown: 0.17.0-beta.6
    typescript: ^5.9.3
    typescript-eslint: ^8.48.0
    valibot: ^1.2.0
    zod: ^4.1.13
  docs:
    hast-util-to-jsx-runtime: ^2.3.6
    react-tweet: ^3.2.2
    remark: ^15.0.1
    remark-gfm: ^4.0.1
    remark-rehype: ^11.1.2
  fumadocs16:
    fumadocs-core: ^16.2.3
    fumadocs-mdx: ^14.1.0
    fumadocs-typescript: ^4.0.13
    fumadocs-ui: ^16.2.3
  linting:
    "@biomejs/biome": ^2.3.8
    "@commitlint/cli": ^20.1.0
    "@commitlint/config-conventional": ^20.0.0
    globals: ^16.5.0
    ultracite: ^6.3.9
  next16:
    "@bprogress/next": ^3.2.12
    "@vercel/analytics": ^1.6.1
    next: ^16.0.7
    next-themes: ^0.4.6
  react19:
    "@vitejs/plugin-react": ^5.1.1
    babel-plugin-react-compiler: ^19.1.0-rc.3
    react: ^19.2.1
    react-dom: ^19.2.1
  tailwind4:
    "@tailwindcss/postcss": ^4.1.17
    "@tailwindcss/vite": ^4.1.17
    postcss: ^8.5.6
    tailwindcss: ^4.1.17
    tw-animate-css: ^1.4.0
  testing:
    "@vitest/coverage-v8": ^4.0.15
    jsdom: ^27.2.0
    vitest: ^4.0.15
  tooling:
    "@changesets/cli": ^2.29.8
    "@turbo/gen": ^2.6.2
    lefthook: ^2.0.7
    rimraf: ^6.1.2
    turbo: ^2.6.2
  types:
    "@types/mdx": ^2.0.13
    "@types/node": ^24.10.1
    "@types/react": ^19.2.7
    "@types/react-dom": ^19.2.3
  ui:
    "@radix-ui/react-dialog": ^1.1.15
    "@radix-ui/react-slot": ^1.2.4
    "@remixicon/react": ^4.7.0
    class-variance-authority: ^0.7.1
    clsx: ^2.1.1
    lucide-react: ^0.555.0
    sonner: ^2.0.7
    tailwind-merge: ^3.4.0
  vite:
    vite: npm:rolldown-vite@^7.2.8
  vitepress:
    "@shikijs/vitepress-twoslash": ^3.19.0
    vitepress: ^1.6.4
    vitepress-plugin-llms: ^1.9.3

onlyBuiltDependencies:
  - "@parcel/watcher"
  - "@swc/core"
  - core-js-pure
  - esbuild
  - lefthook
  - sharp
