packages:
  - apps/*
  - configs/*
  - packages/*

catalog:
  "@better-fetch/fetch": ^1.1.21
  "@fontsource-variable/inter": ^5.2.8
  "@fontsource-variable/jetbrains-mono": ^5.2.8
  "@fontsource/instrument-serif": ^5.2.8
  "@standard-schema/spec": ^1.1.0
  "@tailwindcss/postcss": ^4.2.1
  "@tailwindcss/vite": ^4.2.4
  "@takumi-rs/image-response": ^1.1.2
  "@tanstack/react-router": ^1.168.24
  "@tanstack/react-start": ^1.167.48
  "@types/async-retry": ^1.4.9
  "@types/mdx": ^2.0.13
  "@types/node": ^24.12.2
  "@types/promise-retry": ^1.1.6
  "@types/react": ^19.2.14
  "@types/react-dom": ^19.2.3
  "@vitejs/plugin-react": ^6.0.1
  "@vitest/coverage-v8": ^4.1.5
  arktype: ^2.2.0
  async-retry: ^1.3.3
  axios: ^1.15.2
  better-fetch: ^1.1.2
  exponential-backoff: ^3.1.3
  fumadocs-core: ^16.8.5
  fumadocs-mdx: ^14.3.1
  fumadocs-ui: ^16.8.3
  ky: ^2.0.2
  lucide-react: ^1.11.0
  motion: ^12.38.0
  nitro: 3.0.260415-beta
  ofetch: ^1.5.1
  p-retry: ^8.0.0
  postcss: ^8.5.6
  promise-retry: ^2.0.1
  react: ^19.2.5
  react-dom: ^19.2.5
  tailwind-merge: ^3.5.0
  tailwindcss: ^4.2.4
  typescript: ^6.0.3
  valibot: ^1.3.1
  vite: npm:@voidzero-dev/vite-plus-core@0.1.19
  vite-plus: ^0.1.19
  vitest: npm:@voidzero-dev/vite-plus-test@0.1.19
  zod: ^4.3.6

catalogMode: prefer

onlyBuiltDependencies:
  - "@swc/core"
  - core-js-pure
  - esbuild
  - sharp

overrides:
  vite: "catalog:"
  vitest: "catalog:"

peerDependencyRules:
  allowAny:
    - vite
    - vitest
  allowedVersions:
    vite: "*"
    vitest: "*"
