/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SponsorsRouteImport } from './routes/sponsors'
import { Route as RoadmapRouteImport } from './routes/roadmap'
import { Route as LocalTsRouteImport } from './routes/local-ts'
import { Route as ChangelogsRouteImport } from './routes/changelogs'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PackagesValidationRouteImport } from './routes/packages/validation'
import { Route as PackagesPermitRouteImport } from './routes/packages/permit'
import { Route as PackagesFetchRouteImport } from './routes/packages/fetch'
import { Route as DocsSplatRouteImport } from './routes/docs/$'
import { Route as ChangelogsPackageRouteImport } from './routes/changelogs/$package'
import { Route as ApiSearchRouteImport } from './routes/api/search'
import { Route as Char91llmsTxtChar93IndexRouteImport } from './routes/[llms.txt]/index'
import { Route as Char91llmsFullTxtChar93IndexRouteImport } from './routes/[llms-full.txt]/index'
import { Route as OgDocsSplatRouteImport } from './routes/og/docs/$'
import { Route as Char91llmsMdxChar93DocsSplatRouteImport } from './routes/[llms.mdx]/docs/$'

const SponsorsRoute = SponsorsRouteImport.update({
  id: '/sponsors',
  path: '/sponsors',
  getParentRoute: () => rootRouteImport,
} as any)
const RoadmapRoute = RoadmapRouteImport.update({
  id: '/roadmap',
  path: '/roadmap',
  getParentRoute: () => rootRouteImport,
} as any)
const LocalTsRoute = LocalTsRouteImport.update({
  id: '/local-ts',
  path: '/local-ts',
  getParentRoute: () => rootRouteImport,
} as any)
const ChangelogsRoute = ChangelogsRouteImport.update({
  id: '/changelogs',
  path: '/changelogs',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PackagesValidationRoute = PackagesValidationRouteImport.update({
  id: '/packages/validation',
  path: '/packages/validation',
  getParentRoute: () => rootRouteImport,
} as any)
const PackagesPermitRoute = PackagesPermitRouteImport.update({
  id: '/packages/permit',
  path: '/packages/permit',
  getParentRoute: () => rootRouteImport,
} as any)
const PackagesFetchRoute = PackagesFetchRouteImport.update({
  id: '/packages/fetch',
  path: '/packages/fetch',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsSplatRoute = DocsSplatRouteImport.update({
  id: '/docs/$',
  path: '/docs/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ChangelogsPackageRoute = ChangelogsPackageRouteImport.update({
  id: '/$package',
  path: '/$package',
  getParentRoute: () => ChangelogsRoute,
} as any)
const ApiSearchRoute = ApiSearchRouteImport.update({
  id: '/api/search',
  path: '/api/search',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91llmsTxtChar93IndexRoute =
  Char91llmsTxtChar93IndexRouteImport.update({
    id: '/[llms/txt]/',
    path: '/[llms/txt]/',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91llmsFullTxtChar93IndexRoute =
  Char91llmsFullTxtChar93IndexRouteImport.update({
    id: '/[llms-full/txt]/',
    path: '/[llms-full/txt]/',
    getParentRoute: () => rootRouteImport,
  } as any)
const OgDocsSplatRoute = OgDocsSplatRouteImport.update({
  id: '/og/docs/$',
  path: '/og/docs/$',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91llmsMdxChar93DocsSplatRoute =
  Char91llmsMdxChar93DocsSplatRouteImport.update({
    id: '/[llms/mdx]/docs/$',
    path: '/[llms/mdx]/docs/$',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/changelogs': typeof ChangelogsRouteWithChildren
  '/local-ts': typeof LocalTsRoute
  '/roadmap': typeof RoadmapRoute
  '/sponsors': typeof SponsorsRoute
  '/api/search': typeof ApiSearchRoute
  '/changelogs/$package': typeof ChangelogsPackageRoute
  '/docs/$': typeof DocsSplatRoute
  '/packages/fetch': typeof PackagesFetchRoute
  '/packages/permit': typeof PackagesPermitRoute
  '/packages/validation': typeof PackagesValidationRoute
  '/og/docs/$': typeof OgDocsSplatRoute
  '/[llms-full/txt]/': typeof Char91llmsFullTxtChar93IndexRoute
  '/[llms/txt]/': typeof Char91llmsTxtChar93IndexRoute
  '/[llms/mdx]/docs/$': typeof Char91llmsMdxChar93DocsSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/changelogs': typeof ChangelogsRouteWithChildren
  '/local-ts': typeof LocalTsRoute
  '/roadmap': typeof RoadmapRoute
  '/sponsors': typeof SponsorsRoute
  '/api/search': typeof ApiSearchRoute
  '/changelogs/$package': typeof ChangelogsPackageRoute
  '/docs/$': typeof DocsSplatRoute
  '/packages/fetch': typeof PackagesFetchRoute
  '/packages/permit': typeof PackagesPermitRoute
  '/packages/validation': typeof PackagesValidationRoute
  '/og/docs/$': typeof OgDocsSplatRoute
  '/[llms-full/txt]': typeof Char91llmsFullTxtChar93IndexRoute
  '/[llms/txt]': typeof Char91llmsTxtChar93IndexRoute
  '/[llms/mdx]/docs/$': typeof Char91llmsMdxChar93DocsSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/changelogs': typeof ChangelogsRouteWithChildren
  '/local-ts': typeof LocalTsRoute
  '/roadmap': typeof RoadmapRoute
  '/sponsors': typeof SponsorsRoute
  '/api/search': typeof ApiSearchRoute
  '/changelogs/$package': typeof ChangelogsPackageRoute
  '/docs/$': typeof DocsSplatRoute
  '/packages/fetch': typeof PackagesFetchRoute
  '/packages/permit': typeof PackagesPermitRoute
  '/packages/validation': typeof PackagesValidationRoute
  '/og/docs/$': typeof OgDocsSplatRoute
  '/[llms-full/txt]/': typeof Char91llmsFullTxtChar93IndexRoute
  '/[llms/txt]/': typeof Char91llmsTxtChar93IndexRoute
  '/[llms/mdx]/docs/$': typeof Char91llmsMdxChar93DocsSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/changelogs'
    | '/local-ts'
    | '/roadmap'
    | '/sponsors'
    | '/api/search'
    | '/changelogs/$package'
    | '/docs/$'
    | '/packages/fetch'
    | '/packages/permit'
    | '/packages/validation'
    | '/og/docs/$'
    | '/[llms-full/txt]/'
    | '/[llms/txt]/'
    | '/[llms/mdx]/docs/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/changelogs'
    | '/local-ts'
    | '/roadmap'
    | '/sponsors'
    | '/api/search'
    | '/changelogs/$package'
    | '/docs/$'
    | '/packages/fetch'
    | '/packages/permit'
    | '/packages/validation'
    | '/og/docs/$'
    | '/[llms-full/txt]'
    | '/[llms/txt]'
    | '/[llms/mdx]/docs/$'
  id:
    | '__root__'
    | '/'
    | '/changelogs'
    | '/local-ts'
    | '/roadmap'
    | '/sponsors'
    | '/api/search'
    | '/changelogs/$package'
    | '/docs/$'
    | '/packages/fetch'
    | '/packages/permit'
    | '/packages/validation'
    | '/og/docs/$'
    | '/[llms-full/txt]/'
    | '/[llms/txt]/'
    | '/[llms/mdx]/docs/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ChangelogsRoute: typeof ChangelogsRouteWithChildren
  LocalTsRoute: typeof LocalTsRoute
  RoadmapRoute: typeof RoadmapRoute
  SponsorsRoute: typeof SponsorsRoute
  ApiSearchRoute: typeof ApiSearchRoute
  DocsSplatRoute: typeof DocsSplatRoute
  PackagesFetchRoute: typeof PackagesFetchRoute
  PackagesPermitRoute: typeof PackagesPermitRoute
  PackagesValidationRoute: typeof PackagesValidationRoute
  OgDocsSplatRoute: typeof OgDocsSplatRoute
  Char91llmsFullTxtChar93IndexRoute: typeof Char91llmsFullTxtChar93IndexRoute
  Char91llmsTxtChar93IndexRoute: typeof Char91llmsTxtChar93IndexRoute
  Char91llmsMdxChar93DocsSplatRoute: typeof Char91llmsMdxChar93DocsSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sponsors': {
      id: '/sponsors'
      path: '/sponsors'
      fullPath: '/sponsors'
      preLoaderRoute: typeof SponsorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roadmap': {
      id: '/roadmap'
      path: '/roadmap'
      fullPath: '/roadmap'
      preLoaderRoute: typeof RoadmapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/local-ts': {
      id: '/local-ts'
      path: '/local-ts'
      fullPath: '/local-ts'
      preLoaderRoute: typeof LocalTsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/changelogs': {
      id: '/changelogs'
      path: '/changelogs'
      fullPath: '/changelogs'
      preLoaderRoute: typeof ChangelogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/packages/validation': {
      id: '/packages/validation'
      path: '/packages/validation'
      fullPath: '/packages/validation'
      preLoaderRoute: typeof PackagesValidationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/packages/permit': {
      id: '/packages/permit'
      path: '/packages/permit'
      fullPath: '/packages/permit'
      preLoaderRoute: typeof PackagesPermitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/packages/fetch': {
      id: '/packages/fetch'
      path: '/packages/fetch'
      fullPath: '/packages/fetch'
      preLoaderRoute: typeof PackagesFetchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/$': {
      id: '/docs/$'
      path: '/docs/$'
      fullPath: '/docs/$'
      preLoaderRoute: typeof DocsSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/changelogs/$package': {
      id: '/changelogs/$package'
      path: '/$package'
      fullPath: '/changelogs/$package'
      preLoaderRoute: typeof ChangelogsPackageRouteImport
      parentRoute: typeof ChangelogsRoute
    }
    '/api/search': {
      id: '/api/search'
      path: '/api/search'
      fullPath: '/api/search'
      preLoaderRoute: typeof ApiSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/[llms/txt]/': {
      id: '/[llms/txt]/'
      path: '/[llms/txt]'
      fullPath: '/[llms/txt]/'
      preLoaderRoute: typeof Char91llmsTxtChar93IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/[llms-full/txt]/': {
      id: '/[llms-full/txt]/'
      path: '/[llms-full/txt]'
      fullPath: '/[llms-full/txt]/'
      preLoaderRoute: typeof Char91llmsFullTxtChar93IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/og/docs/$': {
      id: '/og/docs/$'
      path: '/og/docs/$'
      fullPath: '/og/docs/$'
      preLoaderRoute: typeof OgDocsSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/[llms/mdx]/docs/$': {
      id: '/[llms/mdx]/docs/$'
      path: '/[llms/mdx]/docs/$'
      fullPath: '/[llms/mdx]/docs/$'
      preLoaderRoute: typeof Char91llmsMdxChar93DocsSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ChangelogsRouteChildren {
  ChangelogsPackageRoute: typeof ChangelogsPackageRoute
}

const ChangelogsRouteChildren: ChangelogsRouteChildren = {
  ChangelogsPackageRoute: ChangelogsPackageRoute,
}

const ChangelogsRouteWithChildren = ChangelogsRoute._addFileChildren(
  ChangelogsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ChangelogsRoute: ChangelogsRouteWithChildren,
  LocalTsRoute: LocalTsRoute,
  RoadmapRoute: RoadmapRoute,
  SponsorsRoute: SponsorsRoute,
  ApiSearchRoute: ApiSearchRoute,
  DocsSplatRoute: DocsSplatRoute,
  PackagesFetchRoute: PackagesFetchRoute,
  PackagesPermitRoute: PackagesPermitRoute,
  PackagesValidationRoute: PackagesValidationRoute,
  OgDocsSplatRoute: OgDocsSplatRoute,
  Char91llmsFullTxtChar93IndexRoute: Char91llmsFullTxtChar93IndexRoute,
  Char91llmsTxtChar93IndexRoute: Char91llmsTxtChar93IndexRoute,
  Char91llmsMdxChar93DocsSplatRoute: Char91llmsMdxChar93DocsSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
