/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LocalTsRouteImport } from './routes/local-ts'
import { Route as MarketingRouteRouteImport } from './routes/_marketing/route'
import { Route as MarketingIndexRouteImport } from './routes/_marketing/index'
import { Route as PackagesValidationRouteImport } from './routes/packages/validation'
import { Route as PackagesPermitRouteImport } from './routes/packages/permit'
import { Route as PackagesFetchRouteImport } from './routes/packages/fetch'
import { Route as DocsSplatRouteImport } from './routes/docs/$'
import { Route as ApiSearchRouteImport } from './routes/api/search'
import { Route as MarketingSponsorsRouteImport } from './routes/_marketing/sponsors'
import { Route as MarketingRoadmapRouteImport } from './routes/_marketing/roadmap'
import { Route as MarketingChangelogsRouteImport } from './routes/_marketing/changelogs'
import { Route as Char91llmsTxtChar93IndexRouteImport } from './routes/[llms.txt]/index'
import { Route as Char91llmsFullTxtChar93IndexRouteImport } from './routes/[llms-full.txt]/index'
import { Route as MarketingChangelogsPackageRouteImport } from './routes/_marketing/changelogs/$package'
import { Route as Char91llmsMdxChar93DocsSplatRouteImport } from './routes/[llms.mdx]/docs/$'

const LocalTsRoute = LocalTsRouteImport.update({
  id: '/local-ts',
  path: '/local-ts',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketingRouteRoute = MarketingRouteRouteImport.update({
  id: '/_marketing',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketingIndexRoute = MarketingIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MarketingRouteRoute,
} as any)
const PackagesValidationRoute = PackagesValidationRouteImport.update({
  id: '/packages/validation',
  path: '/packages/validation',
  getParentRoute: () => rootRouteImport,
} as any)
const PackagesPermitRoute = PackagesPermitRouteImport.update({
  id: '/packages/permit',
  path: '/packages/permit',
  getParentRoute: () => rootRouteImport,
} as any)
const PackagesFetchRoute = PackagesFetchRouteImport.update({
  id: '/packages/fetch',
  path: '/packages/fetch',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsSplatRoute = DocsSplatRouteImport.update({
  id: '/docs/$',
  path: '/docs/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSearchRoute = ApiSearchRouteImport.update({
  id: '/api/search',
  path: '/api/search',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketingSponsorsRoute = MarketingSponsorsRouteImport.update({
  id: '/sponsors',
  path: '/sponsors',
  getParentRoute: () => MarketingRouteRoute,
} as any)
const MarketingRoadmapRoute = MarketingRoadmapRouteImport.update({
  id: '/roadmap',
  path: '/roadmap',
  getParentRoute: () => MarketingRouteRoute,
} as any)
const MarketingChangelogsRoute = MarketingChangelogsRouteImport.update({
  id: '/changelogs',
  path: '/changelogs',
  getParentRoute: () => MarketingRouteRoute,
} as any)
const Char91llmsTxtChar93IndexRoute =
  Char91llmsTxtChar93IndexRouteImport.update({
    id: '/[llms/txt]/',
    path: '/[llms/txt]/',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91llmsFullTxtChar93IndexRoute =
  Char91llmsFullTxtChar93IndexRouteImport.update({
    id: '/[llms-full/txt]/',
    path: '/[llms-full/txt]/',
    getParentRoute: () => rootRouteImport,
  } as any)
const MarketingChangelogsPackageRoute =
  MarketingChangelogsPackageRouteImport.update({
    id: '/$package',
    path: '/$package',
    getParentRoute: () => MarketingChangelogsRoute,
  } as any)
const Char91llmsMdxChar93DocsSplatRoute =
  Char91llmsMdxChar93DocsSplatRouteImport.update({
    id: '/[llms/mdx]/docs/$',
    path: '/[llms/mdx]/docs/$',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof MarketingIndexRoute
  '/local-ts': typeof LocalTsRoute
  '/changelogs': typeof MarketingChangelogsRouteWithChildren
  '/roadmap': typeof MarketingRoadmapRoute
  '/sponsors': typeof MarketingSponsorsRoute
  '/api/search': typeof ApiSearchRoute
  '/docs/$': typeof DocsSplatRoute
  '/packages/fetch': typeof PackagesFetchRoute
  '/packages/permit': typeof PackagesPermitRoute
  '/packages/validation': typeof PackagesValidationRoute
  '/changelogs/$package': typeof MarketingChangelogsPackageRoute
  '/[llms-full/txt]/': typeof Char91llmsFullTxtChar93IndexRoute
  '/[llms/txt]/': typeof Char91llmsTxtChar93IndexRoute
  '/[llms/mdx]/docs/$': typeof Char91llmsMdxChar93DocsSplatRoute
}
export interface FileRoutesByTo {
  '/local-ts': typeof LocalTsRoute
  '/changelogs': typeof MarketingChangelogsRouteWithChildren
  '/roadmap': typeof MarketingRoadmapRoute
  '/sponsors': typeof MarketingSponsorsRoute
  '/api/search': typeof ApiSearchRoute
  '/docs/$': typeof DocsSplatRoute
  '/packages/fetch': typeof PackagesFetchRoute
  '/packages/permit': typeof PackagesPermitRoute
  '/packages/validation': typeof PackagesValidationRoute
  '/': typeof MarketingIndexRoute
  '/changelogs/$package': typeof MarketingChangelogsPackageRoute
  '/[llms-full/txt]': typeof Char91llmsFullTxtChar93IndexRoute
  '/[llms/txt]': typeof Char91llmsTxtChar93IndexRoute
  '/[llms/mdx]/docs/$': typeof Char91llmsMdxChar93DocsSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_marketing': typeof MarketingRouteRouteWithChildren
  '/local-ts': typeof LocalTsRoute
  '/_marketing/changelogs': typeof MarketingChangelogsRouteWithChildren
  '/_marketing/roadmap': typeof MarketingRoadmapRoute
  '/_marketing/sponsors': typeof MarketingSponsorsRoute
  '/api/search': typeof ApiSearchRoute
  '/docs/$': typeof DocsSplatRoute
  '/packages/fetch': typeof PackagesFetchRoute
  '/packages/permit': typeof PackagesPermitRoute
  '/packages/validation': typeof PackagesValidationRoute
  '/_marketing/': typeof MarketingIndexRoute
  '/_marketing/changelogs/$package': typeof MarketingChangelogsPackageRoute
  '/[llms-full/txt]/': typeof Char91llmsFullTxtChar93IndexRoute
  '/[llms/txt]/': typeof Char91llmsTxtChar93IndexRoute
  '/[llms/mdx]/docs/$': typeof Char91llmsMdxChar93DocsSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/local-ts'
    | '/changelogs'
    | '/roadmap'
    | '/sponsors'
    | '/api/search'
    | '/docs/$'
    | '/packages/fetch'
    | '/packages/permit'
    | '/packages/validation'
    | '/changelogs/$package'
    | '/[llms-full/txt]/'
    | '/[llms/txt]/'
    | '/[llms/mdx]/docs/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/local-ts'
    | '/changelogs'
    | '/roadmap'
    | '/sponsors'
    | '/api/search'
    | '/docs/$'
    | '/packages/fetch'
    | '/packages/permit'
    | '/packages/validation'
    | '/'
    | '/changelogs/$package'
    | '/[llms-full/txt]'
    | '/[llms/txt]'
    | '/[llms/mdx]/docs/$'
  id:
    | '__root__'
    | '/_marketing'
    | '/local-ts'
    | '/_marketing/changelogs'
    | '/_marketing/roadmap'
    | '/_marketing/sponsors'
    | '/api/search'
    | '/docs/$'
    | '/packages/fetch'
    | '/packages/permit'
    | '/packages/validation'
    | '/_marketing/'
    | '/_marketing/changelogs/$package'
    | '/[llms-full/txt]/'
    | '/[llms/txt]/'
    | '/[llms/mdx]/docs/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  MarketingRouteRoute: typeof MarketingRouteRouteWithChildren
  LocalTsRoute: typeof LocalTsRoute
  ApiSearchRoute: typeof ApiSearchRoute
  DocsSplatRoute: typeof DocsSplatRoute
  PackagesFetchRoute: typeof PackagesFetchRoute
  PackagesPermitRoute: typeof PackagesPermitRoute
  PackagesValidationRoute: typeof PackagesValidationRoute
  Char91llmsFullTxtChar93IndexRoute: typeof Char91llmsFullTxtChar93IndexRoute
  Char91llmsTxtChar93IndexRoute: typeof Char91llmsTxtChar93IndexRoute
  Char91llmsMdxChar93DocsSplatRoute: typeof Char91llmsMdxChar93DocsSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/local-ts': {
      id: '/local-ts'
      path: '/local-ts'
      fullPath: '/local-ts'
      preLoaderRoute: typeof LocalTsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_marketing': {
      id: '/_marketing'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof MarketingRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_marketing/': {
      id: '/_marketing/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof MarketingIndexRouteImport
      parentRoute: typeof MarketingRouteRoute
    }
    '/packages/validation': {
      id: '/packages/validation'
      path: '/packages/validation'
      fullPath: '/packages/validation'
      preLoaderRoute: typeof PackagesValidationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/packages/permit': {
      id: '/packages/permit'
      path: '/packages/permit'
      fullPath: '/packages/permit'
      preLoaderRoute: typeof PackagesPermitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/packages/fetch': {
      id: '/packages/fetch'
      path: '/packages/fetch'
      fullPath: '/packages/fetch'
      preLoaderRoute: typeof PackagesFetchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/$': {
      id: '/docs/$'
      path: '/docs/$'
      fullPath: '/docs/$'
      preLoaderRoute: typeof DocsSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/search': {
      id: '/api/search'
      path: '/api/search'
      fullPath: '/api/search'
      preLoaderRoute: typeof ApiSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_marketing/sponsors': {
      id: '/_marketing/sponsors'
      path: '/sponsors'
      fullPath: '/sponsors'
      preLoaderRoute: typeof MarketingSponsorsRouteImport
      parentRoute: typeof MarketingRouteRoute
    }
    '/_marketing/roadmap': {
      id: '/_marketing/roadmap'
      path: '/roadmap'
      fullPath: '/roadmap'
      preLoaderRoute: typeof MarketingRoadmapRouteImport
      parentRoute: typeof MarketingRouteRoute
    }
    '/_marketing/changelogs': {
      id: '/_marketing/changelogs'
      path: '/changelogs'
      fullPath: '/changelogs'
      preLoaderRoute: typeof MarketingChangelogsRouteImport
      parentRoute: typeof MarketingRouteRoute
    }
    '/[llms/txt]/': {
      id: '/[llms/txt]/'
      path: '/[llms/txt]'
      fullPath: '/[llms/txt]/'
      preLoaderRoute: typeof Char91llmsTxtChar93IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/[llms-full/txt]/': {
      id: '/[llms-full/txt]/'
      path: '/[llms-full/txt]'
      fullPath: '/[llms-full/txt]/'
      preLoaderRoute: typeof Char91llmsFullTxtChar93IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_marketing/changelogs/$package': {
      id: '/_marketing/changelogs/$package'
      path: '/$package'
      fullPath: '/changelogs/$package'
      preLoaderRoute: typeof MarketingChangelogsPackageRouteImport
      parentRoute: typeof MarketingChangelogsRoute
    }
    '/[llms/mdx]/docs/$': {
      id: '/[llms/mdx]/docs/$'
      path: '/[llms/mdx]/docs/$'
      fullPath: '/[llms/mdx]/docs/$'
      preLoaderRoute: typeof Char91llmsMdxChar93DocsSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface MarketingChangelogsRouteChildren {
  MarketingChangelogsPackageRoute: typeof MarketingChangelogsPackageRoute
}

const MarketingChangelogsRouteChildren: MarketingChangelogsRouteChildren = {
  MarketingChangelogsPackageRoute: MarketingChangelogsPackageRoute,
}

const MarketingChangelogsRouteWithChildren =
  MarketingChangelogsRoute._addFileChildren(MarketingChangelogsRouteChildren)

interface MarketingRouteRouteChildren {
  MarketingChangelogsRoute: typeof MarketingChangelogsRouteWithChildren
  MarketingRoadmapRoute: typeof MarketingRoadmapRoute
  MarketingSponsorsRoute: typeof MarketingSponsorsRoute
  MarketingIndexRoute: typeof MarketingIndexRoute
}

const MarketingRouteRouteChildren: MarketingRouteRouteChildren = {
  MarketingChangelogsRoute: MarketingChangelogsRouteWithChildren,
  MarketingRoadmapRoute: MarketingRoadmapRoute,
  MarketingSponsorsRoute: MarketingSponsorsRoute,
  MarketingIndexRoute: MarketingIndexRoute,
}

const MarketingRouteRouteWithChildren = MarketingRouteRoute._addFileChildren(
  MarketingRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  MarketingRouteRoute: MarketingRouteRouteWithChildren,
  LocalTsRoute: LocalTsRoute,
  ApiSearchRoute: ApiSearchRoute,
  DocsSplatRoute: DocsSplatRoute,
  PackagesFetchRoute: PackagesFetchRoute,
  PackagesPermitRoute: PackagesPermitRoute,
  PackagesValidationRoute: PackagesValidationRoute,
  Char91llmsFullTxtChar93IndexRoute: Char91llmsFullTxtChar93IndexRoute,
  Char91llmsTxtChar93IndexRoute: Char91llmsTxtChar93IndexRoute,
  Char91llmsMdxChar93DocsSplatRoute: Char91llmsMdxChar93DocsSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
