/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MarketingRouteRouteImport } from './routes/_marketing/route'
import { Route as LlmsFullDottxtRouteImport } from './routes/llms-full[.]txt'
import { Route as LlmsDottxtRouteImport } from './routes/llms[.]txt'
import { Route as MarketingIndexRouteImport } from './routes/_marketing/index'
import { Route as ApiSearchRouteImport } from './routes/api/search'
import { Route as DocsSplatRouteImport } from './routes/docs/$'
import { Route as PackagesFetchRouteImport } from './routes/packages/fetch'
import { Route as PackagesPermitRouteImport } from './routes/packages/permit'
import { Route as PackagesRetryRouteImport } from './routes/packages/retry'
import { Route as PackagesValidationRouteImport } from './routes/packages/validation'
import { Route as PackagesWebhooksRouteImport } from './routes/packages/webhooks'
import { Route as LlmsDotmdxDocsSplatRouteImport } from './routes/llms[.]mdx.docs.$'
import { Route as OgDocsSplatRouteImport } from './routes/og/docs/$'

const MarketingRouteRoute = MarketingRouteRouteImport.update({
  id: '/_marketing',
  getParentRoute: () => rootRouteImport,
} as any)
const LlmsFullDottxtRoute = LlmsFullDottxtRouteImport.update({
  id: '/llms-full.txt',
  path: '/llms-full.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const LlmsDottxtRoute = LlmsDottxtRouteImport.update({
  id: '/llms.txt',
  path: '/llms.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketingIndexRoute = MarketingIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MarketingRouteRoute,
} as any)
const ApiSearchRoute = ApiSearchRouteImport.update({
  id: '/api/search',
  path: '/api/search',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsSplatRoute = DocsSplatRouteImport.update({
  id: '/docs/$',
  path: '/docs/$',
  getParentRoute: () => rootRouteImport,
} as any)
const PackagesFetchRoute = PackagesFetchRouteImport.update({
  id: '/packages/fetch',
  path: '/packages/fetch',
  getParentRoute: () => rootRouteImport,
} as any)
const PackagesPermitRoute = PackagesPermitRouteImport.update({
  id: '/packages/permit',
  path: '/packages/permit',
  getParentRoute: () => rootRouteImport,
} as any)
const PackagesRetryRoute = PackagesRetryRouteImport.update({
  id: '/packages/retry',
  path: '/packages/retry',
  getParentRoute: () => rootRouteImport,
} as any)
const PackagesValidationRoute = PackagesValidationRouteImport.update({
  id: '/packages/validation',
  path: '/packages/validation',
  getParentRoute: () => rootRouteImport,
} as any)
const PackagesWebhooksRoute = PackagesWebhooksRouteImport.update({
  id: '/packages/webhooks',
  path: '/packages/webhooks',
  getParentRoute: () => rootRouteImport,
} as any)
const LlmsDotmdxDocsSplatRoute = LlmsDotmdxDocsSplatRouteImport.update({
  id: '/llms.mdx/docs/$',
  path: '/llms.mdx/docs/$',
  getParentRoute: () => rootRouteImport,
} as any)
const OgDocsSplatRoute = OgDocsSplatRouteImport.update({
  id: '/og/docs/$',
  path: '/og/docs/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof MarketingIndexRoute
  '/llms-full.txt': typeof LlmsFullDottxtRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/api/search': typeof ApiSearchRoute
  '/docs/$': typeof DocsSplatRoute
  '/packages/fetch': typeof PackagesFetchRoute
  '/packages/permit': typeof PackagesPermitRoute
  '/packages/retry': typeof PackagesRetryRoute
  '/packages/validation': typeof PackagesValidationRoute
  '/packages/webhooks': typeof PackagesWebhooksRoute
  '/llms.mdx/docs/$': typeof LlmsDotmdxDocsSplatRoute
  '/og/docs/$': typeof OgDocsSplatRoute
}
export interface FileRoutesByTo {
  '/llms-full.txt': typeof LlmsFullDottxtRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/api/search': typeof ApiSearchRoute
  '/docs/$': typeof DocsSplatRoute
  '/packages/fetch': typeof PackagesFetchRoute
  '/packages/permit': typeof PackagesPermitRoute
  '/packages/retry': typeof PackagesRetryRoute
  '/packages/validation': typeof PackagesValidationRoute
  '/packages/webhooks': typeof PackagesWebhooksRoute
  '/': typeof MarketingIndexRoute
  '/llms.mdx/docs/$': typeof LlmsDotmdxDocsSplatRoute
  '/og/docs/$': typeof OgDocsSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_marketing': typeof MarketingRouteRouteWithChildren
  '/llms-full.txt': typeof LlmsFullDottxtRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/api/search': typeof ApiSearchRoute
  '/docs/$': typeof DocsSplatRoute
  '/packages/fetch': typeof PackagesFetchRoute
  '/packages/permit': typeof PackagesPermitRoute
  '/packages/retry': typeof PackagesRetryRoute
  '/packages/validation': typeof PackagesValidationRoute
  '/packages/webhooks': typeof PackagesWebhooksRoute
  '/_marketing/': typeof MarketingIndexRoute
  '/llms.mdx/docs/$': typeof LlmsDotmdxDocsSplatRoute
  '/og/docs/$': typeof OgDocsSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/llms-full.txt'
    | '/llms.txt'
    | '/api/search'
    | '/docs/$'
    | '/packages/fetch'
    | '/packages/permit'
    | '/packages/retry'
    | '/packages/validation'
    | '/packages/webhooks'
    | '/llms.mdx/docs/$'
    | '/og/docs/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/llms-full.txt'
    | '/llms.txt'
    | '/api/search'
    | '/docs/$'
    | '/packages/fetch'
    | '/packages/permit'
    | '/packages/retry'
    | '/packages/validation'
    | '/packages/webhooks'
    | '/'
    | '/llms.mdx/docs/$'
    | '/og/docs/$'
  id:
    | '__root__'
    | '/_marketing'
    | '/llms-full.txt'
    | '/llms.txt'
    | '/api/search'
    | '/docs/$'
    | '/packages/fetch'
    | '/packages/permit'
    | '/packages/retry'
    | '/packages/validation'
    | '/packages/webhooks'
    | '/_marketing/'
    | '/llms.mdx/docs/$'
    | '/og/docs/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  MarketingRouteRoute: typeof MarketingRouteRouteWithChildren
  LlmsFullDottxtRoute: typeof LlmsFullDottxtRoute
  LlmsDottxtRoute: typeof LlmsDottxtRoute
  ApiSearchRoute: typeof ApiSearchRoute
  DocsSplatRoute: typeof DocsSplatRoute
  PackagesFetchRoute: typeof PackagesFetchRoute
  PackagesPermitRoute: typeof PackagesPermitRoute
  PackagesRetryRoute: typeof PackagesRetryRoute
  PackagesValidationRoute: typeof PackagesValidationRoute
  PackagesWebhooksRoute: typeof PackagesWebhooksRoute
  LlmsDotmdxDocsSplatRoute: typeof LlmsDotmdxDocsSplatRoute
  OgDocsSplatRoute: typeof OgDocsSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_marketing': {
      id: '/_marketing'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof MarketingRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/llms-full.txt': {
      id: '/llms-full.txt'
      path: '/llms-full.txt'
      fullPath: '/llms-full.txt'
      preLoaderRoute: typeof LlmsFullDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/llms.txt': {
      id: '/llms.txt'
      path: '/llms.txt'
      fullPath: '/llms.txt'
      preLoaderRoute: typeof LlmsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_marketing/': {
      id: '/_marketing/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof MarketingIndexRouteImport
      parentRoute: typeof MarketingRouteRoute
    }
    '/api/search': {
      id: '/api/search'
      path: '/api/search'
      fullPath: '/api/search'
      preLoaderRoute: typeof ApiSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/$': {
      id: '/docs/$'
      path: '/docs/$'
      fullPath: '/docs/$'
      preLoaderRoute: typeof DocsSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/packages/fetch': {
      id: '/packages/fetch'
      path: '/packages/fetch'
      fullPath: '/packages/fetch'
      preLoaderRoute: typeof PackagesFetchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/packages/permit': {
      id: '/packages/permit'
      path: '/packages/permit'
      fullPath: '/packages/permit'
      preLoaderRoute: typeof PackagesPermitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/packages/retry': {
      id: '/packages/retry'
      path: '/packages/retry'
      fullPath: '/packages/retry'
      preLoaderRoute: typeof PackagesRetryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/packages/validation': {
      id: '/packages/validation'
      path: '/packages/validation'
      fullPath: '/packages/validation'
      preLoaderRoute: typeof PackagesValidationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/packages/webhooks': {
      id: '/packages/webhooks'
      path: '/packages/webhooks'
      fullPath: '/packages/webhooks'
      preLoaderRoute: typeof PackagesWebhooksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/llms.mdx/docs/$': {
      id: '/llms.mdx/docs/$'
      path: '/llms.mdx/docs/$'
      fullPath: '/llms.mdx/docs/$'
      preLoaderRoute: typeof LlmsDotmdxDocsSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/og/docs/$': {
      id: '/og/docs/$'
      path: '/og/docs/$'
      fullPath: '/og/docs/$'
      preLoaderRoute: typeof OgDocsSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface MarketingRouteRouteChildren {
  MarketingIndexRoute: typeof MarketingIndexRoute
}

const MarketingRouteRouteChildren: MarketingRouteRouteChildren = {
  MarketingIndexRoute: MarketingIndexRoute,
}

const MarketingRouteRouteWithChildren = MarketingRouteRoute._addFileChildren(
  MarketingRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  MarketingRouteRoute: MarketingRouteRouteWithChildren,
  LlmsFullDottxtRoute: LlmsFullDottxtRoute,
  LlmsDottxtRoute: LlmsDottxtRoute,
  ApiSearchRoute: ApiSearchRoute,
  DocsSplatRoute: DocsSplatRoute,
  PackagesFetchRoute: PackagesFetchRoute,
  PackagesPermitRoute: PackagesPermitRoute,
  PackagesRetryRoute: PackagesRetryRoute,
  PackagesValidationRoute: PackagesValidationRoute,
  PackagesWebhooksRoute: PackagesWebhooksRoute,
  LlmsDotmdxDocsSplatRoute: LlmsDotmdxDocsSplatRoute,
  OgDocsSplatRoute: OgDocsSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
