name: Setup nub

runs:
  using: composite
  steps:
    - name: Setup nub
      uses: nubjs/setup-nub@v0
      with:
        cache-dependency-path: nub.lock
    - name: Install dependencies
      shell: bash
      run: nub ci
