import type { CorePluginId, OptionalPluginId, Plugin, PluginId } from './types';

/* TODO: review data and add which plugins depend on each other */

export const CorePluginIds = {
  api: 'api',
  auth: 'auth',
  components: 'components',
  crypto: 'crypto',
  db: 'db',
  env: 'env',
  errors: 'errors',
  mails: 'mails',
  payments: 'payments',
  plugins: 'plugins',
} as const;

export const OptionalPluginIds = {
  ai: 'ai',
  analytics: 'analytics',
  blog: 'blog',
  feedbacks: 'feedbacks',
  flags: 'flags',
  landing: 'landing',
  legal: 'legal',
  markdown: 'markdown',
  pwa: 'pwa',
  sidebar: 'sidebar',
  waitlist: 'waitlist',
} as const;

export const corePlugins: Record<CorePluginId, Plugin> = {
  api: {
    id: 'api',
    label: 'API',
    description: 'Typed RPC API using oRPC.',
    dependencies: ['@orpc/client', '@orpc/server', '@orpc/react-query'],
    devDependencies: [],
    requiredPlugins: [],
  },
  auth: {
    id: 'auth',
    label: 'Authentication',
    description: 'Authentication with Better Auth.',
    dependencies: ['better-auth', '@polar-sh/better-auth', '@polar-sh/sdk'],
    devDependencies: [],
    requiredPlugins: [],
  },
  components: {
    id: 'components',
    label: 'Components',
    description: 'Extra UI hooks and utilities for shadcn/ui.',
    dependencies: ['clsx', 'tailwind-merge', 'class-variance-authority'],
    devDependencies: [],
    requiredPlugins: [],
  },
  crypto: {
    id: 'crypto',
    label: 'Crypto',
    description: 'Cryptographic helpers and utilities.',
    dependencies: [],
    devDependencies: [],
    requiredPlugins: [],
  },
  db: {
    id: 'db',
    label: 'Database',
    description: 'Database integration via Drizzle ORM & PostgreSQL.',
    dependencies: ['drizzle-orm', 'pg', '@neondatabase/serverless'],
    devDependencies: ['drizzle-kit'],
    requiredPlugins: [],
  },
  env: {
    id: 'env',
    label: 'Environment',
    description: 'Environment management via dotenv.',
    dependencies: ['dotenv'],
    devDependencies: [],
    requiredPlugins: [],
  },
  errors: {
    id: 'errors',
    label: 'Error Handling',
    description: 'Error boundary & toast system.',
    dependencies: ['sonner', 'zod'],
    devDependencies: [],
    requiredPlugins: [],
  },
  mails: {
    id: 'mails',
    label: 'Emails',
    description: 'Email templates with React Email & Resend.',
    dependencies: ['@react-email/components', 'react-email', 'resend'],
    devDependencies: ['@react-email/preview-server'],
    requiredPlugins: [],
  },
  payments: {
    id: 'payments',
    label: 'Payments',
    description: 'Billing & payments with Polar SDK.',
    dependencies: ['@polar-sh/sdk', '@polar-sh/better-auth'],
    devDependencies: [],
    requiredPlugins: [],
  },
  plugins: {
    id: 'plugins',
    label: 'Plugins',
    description: 'Zap.ts plugin system bootstrap.',
    dependencies: [],
    devDependencies: [],
    requiredPlugins: [],
  },
};

export const optionalPlugins: Record<OptionalPluginId, Plugin> = {
  ai: {
    id: 'ai',
    label: 'AI',
    description: 'Integrates AI SDKs such as OpenAI and Mistral.',
    dependencies: ['ai', '@ai-sdk/openai', '@ai-sdk/mistral', '@ai-sdk/react'],
    devDependencies: [],
    requiredPlugins: [],
  },
  analytics: {
    id: 'analytics',
    label: 'Analytics',
    description: 'Adds analytics providers like Vercel, PostHog, etc.',
    dependencies: [
      '@vercel/analytics',
      '@vercel/speed-insights',
      'posthog-js',
      'posthog-node',
    ],
    devDependencies: [],
    requiredPlugins: [],
  },
  blog: {
    id: 'blog',
    label: 'Blog',
    description: 'Static/dynamic blog with MDX support.',
    dependencies: [
      'next-mdx-remote',
      'gray-matter',
      '@mdx-js/react',
      '@mdx-js/loader',
    ],
    devDependencies: [],
    requiredPlugins: [],
  },
  feedbacks: {
    id: 'feedbacks',
    label: 'Feedback',
    description: 'Collect feedback from users.',
    dependencies: [],
    devDependencies: [],
    requiredPlugins: [],
  },
  flags: {
    id: 'flags',
    label: 'Feature Flags',
    description: 'Feature flagging with Flags SDK + PostHog.',
    dependencies: ['flags', '@flags-sdk/posthog'],
    devDependencies: [],
    requiredPlugins: [],
  },
  landing: {
    id: 'landing',
    label: 'Landing',
    description: 'Public landing page template.',
    dependencies: [],
    devDependencies: [],
    requiredPlugins: [],
  },
  legal: {
    id: 'legal',
    label: 'Legal',
    description: 'Cookie, privacy, terms of service pages.',
    dependencies: [],
    devDependencies: [],
    requiredPlugins: [],
  },
  markdown: {
    id: 'markdown',
    label: 'Markdown',
    description: 'Markdown rendering with syntax highlighting.',
    dependencies: ['react-syntax-highlighter', 'gray-matter'],
    devDependencies: [],
    requiredPlugins: [],
  },
  pwa: {
    id: 'pwa',
    label: 'Progressive Web App',
    description: 'Service worker, manifest, push notifications.',
    dependencies: ['web-push'],
    devDependencies: [],
    requiredPlugins: [],
  },
  sidebar: {
    id: 'sidebar',
    label: 'Sidebar Layout',
    description: 'Authenticated app layout with sidebar.',
    dependencies: [],
    devDependencies: [],
    requiredPlugins: [],
  },
  waitlist: {
    id: 'waitlist',
    label: 'Waitlist',
    description: 'Waitlist page + middleware integration.',
    dependencies: [],
    devDependencies: [],
    requiredPlugins: [],
  },
};

export const plugins: Record<PluginId, Plugin> = {
  ...corePlugins,
  ...optionalPlugins,
};
