import type { RuleMap } from "./_prefixed.ts";

export const reactA11yRules: RuleMap = {
  "alt-text": "error",
  "anchor-ambiguous-text": "warn",
  "anchor-has-content": "warn",
  "anchor-is-valid": "warn",
  "aria-activedescendant-has-tabindex": "warn",
  "aria-props": "error",
  "aria-proptypes": "error",
  "aria-role": "error",
  "aria-unsupported-elements": "error",
  "autocomplete-valid": "warn",
  "click-events-have-key-events": "warn",
  "control-has-associated-label": "warn",
  "heading-has-content": "warn",
  "html-has-lang": "warn",
  "iframe-has-title": "warn",
  "img-redundant-alt": "warn",
  "interactive-supports-focus": "warn",
  "label-has-associated-control": "warn",
  "media-has-caption": "warn",
  "mouse-events-have-key-events": "warn",
  "no-access-key": "warn",
  "no-aria-hidden-on-focusable": "warn",
  "no-autofocus": "warn",
  "no-distracting-elements": "error",
  "no-interactive-element-to-noninteractive-role": "warn",
  "no-noninteractive-element-interactions": "warn",
  "no-noninteractive-element-to-interactive-role": "warn",
  "no-noninteractive-tabindex": "warn",
  "no-redundant-roles": "warn",
  "no-static-element-interactions": "warn",
  "prefer-tag-over-role": "warn",
  "role-has-required-aria-props": "error",
  "role-supports-aria-props": "warn",
  "tabindex-no-positive": "warn",

  // this repo's UI packages set `lang`/`scope` at the framework/template level, not
  // per-element — see reactDoctorRules' history for the original off-call
  lang: "off",
  scope: "off",
};
