import type { RuleMap } from "./_prefixed.ts";

export const reactDoctorNextjsRules = {
  "nextjs-async-client-component": "error",
  "nextjs-async-dynamic-api-not-awaited": "error",
  "nextjs-error-boundary-missing-use-client": "error",
  "nextjs-global-error-missing-html-body": "error",
  "nextjs-image-missing-sizes": "warn",
  "nextjs-inline-script-missing-id": "warn",
  "nextjs-metadata-url-consistency": "warn",
  "nextjs-missing-metadata": "warn",
  "nextjs-no-a-element": "warn",
  "nextjs-no-client-fetch-for-server-data": "warn",
  "nextjs-no-client-side-redirect": "warn",
  "nextjs-no-css-link": "warn",
  "nextjs-no-default-export-in-route-handler": "error",
  "nextjs-no-edge-og-runtime": "warn",
  "nextjs-no-font-link": "warn",
  "nextjs-no-google-analytics-script": "warn",
  "nextjs-no-head-import": "error",
  "nextjs-no-img-element": "warn",
  "nextjs-no-native-script": "warn",
  "nextjs-no-polyfill-script": "warn",
  "nextjs-no-redirect-in-try-catch": "warn",
  "nextjs-no-script-in-head": "error",
  "nextjs-no-side-effect-in-get-handler": "error",
  "nextjs-no-use-search-params-without-suspense": "warn",
  "nextjs-no-vercel-og-import": "warn",
} satisfies RuleMap;
