import type { RuleMap } from "./_prefixed.ts";

export const reactDoctorReactNativeRules: RuleMap = {
  "expo-no-non-inlined-env": "warn",
  "rn-animation-reaction-as-derived": "warn",
  "rn-bottom-sheet-no-ignored-scroll-prop": "warn",
  "rn-bottom-sheet-no-state-in-on-animate": "warn",
  "rn-bottom-sheet-prefer-native": "warn",
  "rn-bottom-sheet-use-integrated-scrollable": "warn",
  "rn-detox-missing-await": "warn",
  "rn-list-callback-per-row": "warn",
  "rn-list-data-mapped": "warn",
  "rn-list-missing-estimated-item-size": "warn",
  "rn-list-recyclable-without-types": "warn",
  "rn-no-deep-imports": "warn",
  "rn-no-deprecated-modules": "error",
  "rn-no-dimensions-get": "warn",
  "rn-no-falsy-and-render": "error",
  "rn-no-image-children": "error",
  "rn-no-inline-flatlist-renderitem": "warn",
  "rn-no-inline-object-in-list-item": "warn",
  "rn-no-legacy-expo-packages": "warn",
  "rn-no-legacy-shadow-styles": "warn",
  "rn-no-non-native-navigator": "warn",
  "rn-no-panresponder": "warn",
  "rn-no-raw-text": "error",
  "rn-no-renderitem-key": "warn",
  "rn-no-scroll-state": "error",
  "rn-no-scrollview-mapped-list": "warn",
  "rn-no-set-native-props": "warn",
  "rn-no-single-element-style-array": "warn",
  "rn-platform-shaking-use-direct-import": "warn",
  "rn-prefer-expo-image": "warn",
  "rn-prefer-pressable": "warn",
  "rn-prefer-pressable-over-gesture-detector": "warn",
  "rn-prefer-reanimated": "warn",
  "rn-pressable-shared-value-mutation": "warn",
  "rn-reanimated-4-no-legacy-spring-thresholds": "warn",
  "rn-reanimated-4-no-removed-api": "warn",
  "rn-reanimated-4-use-worklets-scheduler": "warn",
  "rn-scrollview-dynamic-padding": "warn",
  "rn-scrollview-flex-in-content-container": "warn",
  "rn-style-prefer-boxshadow": "warn",

  // retired upstream — always a no-op per the rule's own metadata
  "rn-animate-layout-property": "off",
  "rn-prefer-content-inset-adjustment": "off",
};
