import type { RuleMap } from "./_prefixed.ts";

export const reactDoctorReactRouterRules = {
  "react-router-csp-nonce-consistency": "error",
  "react-router-descendant-routes-require-splat": "error",
  "react-router-guard-aborted-handle-error": "warn",
  "react-router-internal-route-anchor": "warn",
  "react-router-loader-fetch-forwards-signal": "warn",
  "react-router-loader-parallel-fetch": "warn",
  "react-router-nested-route-requires-outlet": "error",
  "react-router-no-catch-middleware-next": "warn",
  "react-router-no-client-module-in-server-render": "error",
  "react-router-no-duplicate-route-id": "error",
  "react-router-no-empty-leaf-route": "warn",
  "react-router-no-invalid-absolute-child-path": "error",
  "react-router-no-invalid-lazy-route-properties": "error",
  "react-router-no-invalid-splat-path": "error",
  "react-router-no-loader-request-body": "error",
  "react-router-no-middleware-response-body-consumption": "warn",
  "react-router-no-multiple-blockers": "error",
  "react-router-no-multiple-middleware-next": "error",
  "react-router-no-multiple-set-search-params-in-tick": "warn",
  "react-router-no-navigate-in-render": "error",
  "react-router-no-nested-router": "error",
  "react-router-no-redirect-in-try-catch": "error",
  "react-router-no-route-module-environment-suffix": "error",
  "react-router-no-router-in-render": "error",
  "react-router-no-session-mutation-in-loader": "error",
  "react-router-no-static-cookie-expires": "error",
  "react-router-no-unsynchronized-search-params-mutation": "error",
  "react-router-no-use-loader-data-in-error-ui": "error",
  "react-router-prefer-route-lazy": "warn",
  "react-router-require-root-error-boundary": "error",
  "react-router-resource-link-requires-reload": "error",
  "react-router-return-navigation-promise-in-transition": "warn",
  "react-router-server-middleware-return-response": "error",
  "react-router-session-mutation-requires-commit": "error",
  "react-router-v8-no-meta-data-field": "error",
  "react-router-v8-no-react-router-dom-import": "error",
  "react-router-v8-no-removed-future-flags": "error",
  "react-router-valid-route-object": "error",
} satisfies RuleMap;
