import type { RuleMap } from "./_prefixed.ts";

export const regexpRules: RuleMap = {
  "confusing-quantifier": "warn",
  "control-character-escape": "error",
  "match-any": "error",
  negation: "error",
  "no-contradiction-with-assertion": "error",
  "no-control-character": "error",
  "no-dupe-characters-character-class": "error",
  "no-dupe-disjunctions": "error",
  "no-empty-alternative": "warn",
  "no-empty-capturing-group": "error",
  "no-empty-character-class": "error",
  "no-empty-group": "error",
  "no-empty-lookarounds-assertion": "error",
  "no-empty-string-literal": "error",
  "no-escape-backspace": "error",
  "no-extra-lookaround-assertions": "error",
  "no-invalid-regexp": "error",
  "no-invisible-character": "error",
  "no-lazy-ends": "warn",
  "no-legacy-features": "error",
  "no-misleading-capturing-group": "error",
  "no-misleading-unicode-character": "error",
  "no-missing-g-flag": "error",
  "no-non-standard-flag": "error",
  "no-obscure-range": "error",
  "no-octal": "error",
  "no-optional-assertion": "error",
  "no-potentially-useless-backreference": "warn",
  "no-standalone-backslash": "error",
  "no-super-linear-backtracking": "error",
  "no-super-linear-move": "error",
  "no-trivially-nested-assertion": "error",
  "no-trivially-nested-quantifier": "error",
  "no-unused-capturing-group": "error",
  "no-useless-assertions": "error",
  "no-useless-backreference": "error",
  "no-useless-character-class": "error",
  "no-useless-dollar-replacements": "error",
  "no-useless-escape": "error",
  "no-useless-flag": "warn",
  "no-useless-lazy": "error",
  "no-useless-non-capturing-group": "error",
  "no-useless-quantifier": "error",
  "no-useless-range": "error",
  "no-useless-set-operand": "error",
  "no-useless-string-literal": "error",
  "no-useless-two-nums-quantifier": "error",
  "no-zero-quantifier": "error",
  "optimal-lookaround-quantifier": "warn",
  "optimal-quantifier-concatenation": "error",
  "prefer-character-class": "error",
  "prefer-d": "error",
  "prefer-escape-replacement-dollar-char": "error",
  "prefer-lookaround": "error",
  "prefer-named-backreference": "error",
  "prefer-plus-quantifier": "error",
  "prefer-predefined-assertion": "error",
  "prefer-quantifier": "error",
  "prefer-question-quantifier": "error",
  "prefer-range": "error",
  "prefer-regexp-exec": "error",
  "prefer-regexp-test": "error",
  "prefer-result-array-groups": "error",
  "prefer-set-operation": "error",
  "prefer-star-quantifier": "error",
  "prefer-unicode-codepoint-escapes": "error",
  "prefer-w": "error",
  "require-unicode-regexp": "error",
  "simplify-set-operations": "error",
  "sort-flags": "error",
  strict: "error",
  "use-ignore-case": "error",

  // cosmetic ordering/casing preferences — oxfmt's territory, not the linter's
  "hexadecimal-escape": "off",
  "letter-case": "off",
  "sort-alternatives": "off",
  "sort-character-class-elements": "off",
  "unicode-escape": "off",
  "unicode-property": "off",
  // no autofix, opinionated, noisy on simple 1-2-group regexes
  "prefer-named-capture-group": "off",
  // the `v` flag (ES2024) is too new/niche for a general preset; `u`
  // (require-unicode-regexp, enabled above) already covers the correctness wins
  "require-unicode-sets-regexp": "off",
  // niche (multi-codepoint grapheme mismatches), no autofix, low confidence
  // this earns its keep as a blanket default
  "grapheme-string-literal": "off",
};
