import type { RuleMap } from "./_prefixed.ts";

export const e18eRules: RuleMap = {
  "ban-dependencies": "error",
  "no-delete-property": "error",
  "no-spread-in-reduce": "error",
  "prefer-array-at": "error",
  "prefer-array-fill": "error",
  "prefer-array-from-map": "error",
  "prefer-array-some": "error",
  "prefer-array-to-reversed": "error",
  "prefer-array-to-sorted": "error",
  "prefer-array-to-spliced": "error",
  "prefer-charcode-at-in-loop": "error",
  "prefer-date-now": "error",
  "prefer-exponentiation-operator": "error",
  "prefer-flatmap-over-map-flat": "error",
  "prefer-get-or-insert": "error",
  "prefer-includes": "error",
  "prefer-includes-over-regex-test": "error",
  "prefer-inline-equality": "error",
  "prefer-nullish-coalescing": "error",
  "prefer-object-has-own": "error",
  "prefer-regex-test": "error",
  "prefer-slice-over-split-index": "error",
  "prefer-spread-syntax": "error",
  "prefer-static-collator": "error",
  "prefer-static-regex": "error",
  "prefer-string-fromcharcode": "error",
  "prefer-throw-if-no-entry": "error",
  "prefer-timer-args": "error",
  "prefer-url-canparse": "error",

  "no-indexof-equality": "off",
};
