name: Setup pnpm

runs:
  using: composite
  steps:
    - name: Setup pnpm
      uses: pnpm/action-setup@v4
      with:
        version: 11.21.0
    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: 24
        cache: pnpm
    - name: Install dependencies
      shell: bash
      run: pnpm install --frozen-lockfile
