name: Check

on:
  pull_request:
    branches: ["**"]
    types: [opened, synchronize, reopened, ready_for_review]
    paths-ignore:
      - "apps/docs/content/**"
      - ".changeset/**"
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: ci-check-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  check-monorepo:
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch' || github.event.pull_request.draft == false
    steps:
      - uses: actions/checkout@v6
      - name: Setup Vite+
        uses: ./.github/actions/setup-vp

      - name: Run check on the monorepo
        run: vp check
