name: Typecheck

on:
  pull_request:
    branches: ["**"]
    types: [opened, synchronize, reopened, ready_for_review]
    paths-ignore:
      - "**/*.md"
      - "apps/docs/content/**"
      - ".changeset/**"
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: ci-typecheck-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  typecheck-monorepo:
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch' || github.event.pull_request.draft == false
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - name: Setup Vite+
        uses: ./.github/actions/setup-vp

      - name: Build monorepo
        run: vp run -r build

      - name: Run typecheck on the monorepo
        run: vp run -r typecheck
